# Generated by Django 5.2 on 2025-04-09 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='payment_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='release',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='release',
            name='featuring_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_releases', to='api.artist'),
        ),
        migrations.AddField(
            model_name='release',
            name='google_drive_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='release',
            name='main_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_releases', to='api.artist'),
        ),
        migrations.AddField(
            model_name='release',
            name='pre_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='type',
            field=models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('single', 'Single'), ('compilation', 'Compilation')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='featuring_artists',
            field=models.ManyToManyField(blank=True, related_name='featured_tracks', to='api.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='remix_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixed_tracks', to='api.artist'),
        ),
    ]
