version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=label_manager
    restart: always

  # Django Backend
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      - DEBUG=0
      - SECRET_KEY=your_production_secret_key_here
      - DATABASE_URL=postgres://postgres_user:postgres_password@db:5432/label_manager
      - ALLOWED_HOSTS=localhost,127.0.0.1,yourdomain.com
      - CORS_ALLOWED_ORIGINS=http://localhost,https://yourdomain.com
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    # Ensure gunicorn is installed in requirements.txt

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
    # The nginx config in the frontend container will proxy requests to the backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
