# Generated by Django 5.2 on 2025-09-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_artist_payment_address_release_cover_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vendor_key', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('release', 'release'), ('track', 'track')], max_length=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('basis', models.CharField(choices=[('gross', 'gross'), ('net', 'net'), ('platform_net', 'platform_net')], default='net', max_length=20)),
                ('default_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.label')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.release')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.track')),
            ],
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'main'), ('featured', 'featured'), ('remixer', 'remixer'), ('label', 'label')], default='main', max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('payee_name', models.CharField(blank=True, max_length=200)),
                ('payee_currency', models.CharField(blank=True, max_length=3)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='finances.contract')),
            ],
        ),
        migrations.CreateModel(
            name='CostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('base_ccy', models.CharField(default='EUR', max_length=3)),
                ('amount_base', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.label')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.release')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.track')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.platform')),
            ],
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_ccy', models.CharField(max_length=3)),
                ('to_ccy', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=9, max_digits=18)),
            ],
            options={
                'unique_together': {('date', 'from_ccy', 'to_ccy')},
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.label')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField()),
                ('period_quarter', models.IntegerField()),
                ('base_currency', models.CharField(default='EUR', max_length=3)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.label')),
            ],
            options={
                'unique_together': {('label', 'period_year', 'period_quarter')},
            },
        ),
        migrations.CreateModel(
            name='RecoupmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('advance', 'advance'), ('cost_pool', 'cost_pool')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.contract')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('product_type', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('publisher_deduction', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('marketplace_fees', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('transaction_fees', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('base_ccy', models.CharField(default='EUR', max_length=3)),
                ('net_amount_base', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('isrc', models.CharField(blank=True, max_length=32)),
                ('upc_ean', models.CharField(blank=True, max_length=32)),
                ('label_order_nr', models.CharField(blank=True, max_length=64)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.country')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.label')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.platform')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.release')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.track')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base', models.DecimalField(decimal_places=6, max_digits=18)),
                ('amount_original', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('original_currency', models.CharField(blank=True, max_length=3)),
                ('fx_rate_used', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contract')),
                ('cost_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.costevent')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.release')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.track')),
                ('payout_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finances.payoutrun')),
                ('revenue_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.revenueevent')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('bytes', models.BigIntegerField()),
                ('mtime', models.DateTimeField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('statement_type', models.CharField(max_length=32)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.sourcefile')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.datasource')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='api.label')),
            ],
        ),
        migrations.AddField(
            model_name='revenueevent',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.sourcefile'),
        ),
        migrations.AddField(
            model_name='costevent',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.sourcefile'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor_key', models.CharField(blank=True, max_length=100)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='finances.platform')),
            ],
        ),
        migrations.AddField(
            model_name='revenueevent',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.store'),
        ),
        migrations.CreateModel(
            name='PlatformRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc_ean', models.CharField(blank=True, max_length=32)),
                ('label_order_nr', models.CharField(blank=True, max_length=64)),
                ('external_ids', models.JSONField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.platform')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.release')),
            ],
            options={
                'unique_together': {('release', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='PlatformTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isrc', models.CharField(blank=True, max_length=32)),
                ('external_ids', models.JSONField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.platform')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track')),
            ],
            options={
                'unique_together': {('track', 'platform')},
            },
        ),
        migrations.AddIndex(
            model_name='sourcefile',
            index=models.Index(fields=['label', 'statement_type', 'period_start', 'period_end'], name='finances_so_label_i_a2574c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('platform', 'name')},
        ),
        migrations.AddIndex(
            model_name='revenueevent',
            index=models.Index(fields=['label', 'occurred_at'], name='finances_re_label_i_799210_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueevent',
            index=models.Index(fields=['platform', 'store'], name='finances_re_platfor_d56acc_idx'),
        ),
    ]
