# Generated by Django 5.2 on 2025-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueevent',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='revenueevent',
            name='track_artist_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='revenueevent',
            name='track_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
