# Generated by Django 5.2 on 2025-09-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_star_schema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DwArtist',
        ),
        migrations.DeleteModel(
            name='DwRelease',
        ),
        migrations.DeleteModel(
            name='DwTrack',
        ),
        migrations.AlterModelOptions(
            name='dwfactrevenue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rawbandcampevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rawlabelworxevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rawzebralutionevent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stagingdistributionevent',
            options={'managed': False},
        ),
    ]
